- externalId: market_configuration_nord_pool_day_ahead
  sources:
  - properties:
      maxPrice: 4000
      minPrice: -500
      name: Nord Pool Day-Ahead
      priceSteps: 200
      priceUnit: EUR/MWh
      tickSize: 0.1
      timeUnit: 1h
      timezone: Europe/Oslo
      tradeLot: 0.1
    source:
      externalId: MarketConfiguration
      space: power_ops_core
      type: view
      version: '1'
  space: power_ops_instances
  type:
    externalId: MarketConfiguration
    space: power_ops_types
- externalId: market_configuration_nord_pool_day_ahead_15_min
  sources:
  - properties:
      maxPrice: 4000
      minPrice: -500
      name: Nord Pool Day-Ahead 15 min
      priceSteps: 200
      priceUnit: EUR/MWh
      tickSize: 0.1
      timeUnit: 15m
      timezone: Europe/Oslo
      tradeLot: 0.1
    source:
      externalId: MarketConfiguration
      space: power_ops_core
      type: view
      version: '1'
  space: power_ops_instances
  type:
    externalId: MarketConfiguration
    space: power_ops_types
