name: Toolkit Deploy Staging

on:
  push:
    branches:
      - "main"
    paths:
      - "toolkit/**"
      - ".github/workflows/toolkit-staging.yaml"
      - "!**/*.md"

env:
  TOOLKIT_VERSION: 0.5.94
  PYTHON_VERSION: "3.11"
  CLIENT_CONFIG_FILE: "power_ops_config.yaml"
  CONFIGURATION_FILE: "resync/configuration.yaml"

jobs:
  get-toolkit-version:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image.outputs.image }}
    steps:
      - id: image
        run: echo "image=cognite/toolkit:$TOOLKIT_VERSION" >> "$GITHUB_OUTPUT"
  deploy-modules:
    name: Toolkit build and deploy staging
    needs: get-toolkit-version
    runs-on: ubuntu-latest
    environment: power-ops-staging
    container:
      image: ${{ needs.get-toolkit-version.outputs.image }}
      env:
        LOGIN_FLOW: client_credentials
        CDF_PROJECT: power-ops-staging
        CDF_CLUSTER: ${{ secrets.CLUSTER }}
        IDP_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        IDP_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        IDP_TENANT_ID: ${{ secrets.TENANT_ID }}
        WF_TRIGGER_SECRET: ${{ secrets.WF_TRIGGER_SECRET }}
        TOOLKIT_ENV: ${{ secrets.TOOLKIT_ENV}}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Build modules
        run: cdf build --env $TOOLKIT_ENV --build-dir cdf-tk-build
      - name: Deploy modules
        run: cdf deploy cdf-tk-build

  resync-purge:
    name: Resync Purge to CDF project power-ops-staging
    needs: deploy-modules
    environment:
      name: power-ops-staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip poetry==2.*
          poetry config virtualenvs.create false
          poetry install
      - name: Run resync purge
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          PROJECT: power-ops-staging
          CLUSTER: ${{ secrets.CLUSTER }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
        run: |
          echo Running resync purge in CDF environment $PROJECT
          powerops purge $CLIENT_CONFIG_FILE $CONFIGURATION_FILE
